services:
  ecsdeploy:
    build: .
    env_file:
      - path: local.env
        required: false
    volumes:
      - ./ecs-deploy:/ecs-deploy

  test:
    build: .
    env_file:
      - path: local.env
        required: false
    entrypoint: ["/run-tests.sh"]
    volumes:
      - ./ecs-deploy:/ecs-deploy
      - ./run-tests.sh:/run-tests.sh
      - ./test.bats:/test.bats
